approve_label: "approved"
problem_label: "needs some work"
ignore_label: "skip validation"

allowed_targets: ["dev", "bugfix", "next"]
forbidden_sources: [
    # new branching strategy
    "main",
    "bugfix",
    "next",
    "dev",
    # old branching strategy
    "master",
    "maintenance",
    "devel",
    "staging/bugfix",
    "staging/maintenance",
    "staging/devel"
  ]

labels:
  docs:
    additional_allowed_targets: ["main"]
  meta:
    additional_allowed_targets: ["main"]
  ci/cd:
    additional_allowed_targets: ["main"]

check_can_modify: true
create_review: true
