approve_label: "approved"
problem_label: "needs some work"
ignore_label: "skip validation"

allowed_targets: ["maintenance", "devel", "staging/maintenance", "staging/devel"]
forbidden_sources:
  ["master", "maintenance", "devel", "staging/maintenance", "staging/devel"]

labels:
  docs:
    additional_allowed_targets: ["master"]
  meta:
    additional_allowed_targets: ["master"]
  ci/cd:
    additional_allowed_targets: ["master"]

check_can_modify: true
create_review: true
