parserOptions:
  ecmaVersion: 2018

overrides:
  - files:
      - "src/octoprint/static/js/**.js"
      - "src/octoprint/plugins/**.js"
    env:
      browser: true
      jquery: true
      es6: true
  - files:
      - "tests/cypress/**"
    env:
      node: true
      es6: true
      cypress/globals: true
    extends:
      - "plugin:cypress/recommended"

plugins:
  - cypress
