overrides:
  - files:
      - "src/octoprint/static/js/app/**"
    env:
      browser: true
      jquery: true
    parserOptions:
      ecmaVersion: 5
    rules:
      es5/no-arrow-functions: error
      es5/no-binary-and-octal-literals: error
      es5/no-block-scoping: error
      es5/no-classes: error
      es5/no-computed-properties: error
      es5/no-default-parameters: error
      es5/no-destructuring: error
      es5/no-exponentiation-operator: error
      es5/no-for-of: error
      es5/no-generators: error
      es5/no-modules: error
      es5/no-object-super: error
      es5/no-rest-parameters: error
      es5/no-shorthand-properties: error
      es5/no-spread: error
      es5/no-template-literals: error
      es5/no-typeof-symbol: error
      es5/no-unicode-code-point-escape: error
      es5/no-unicode-regex: error
  - files:
      - "tests/cypress/**"
    env:
      node: true
      es6: true
      cypress/globals: true
    extends:
      - "plugin:cypress/recommended"

plugins:
  - eslint-plugin-es5
  - cypress
