[pytest]
testpaths = src tests
addopts = --doctest-modules
          --doctest-repr=octoprint.util:pp
          --ignore=src/octoprint/vendor
          -m "not http_api"
markers =
    time_machine
    http_api
