[pytest]
testpaths = src tests
addopts = --doctest-modules
          --doctest-repr=octoprint.util:pp
          --ignore=src/octoprint/vendor
          --ignore=src/octoprint/util/comm.py
          -m "not http_api"
markers =
    time_machine
    http_api
filterwarnings =
    error
