(start of end.gcode)
M104 S0                (extruder heat off)
M106                   (fan on)
G91                    (relative positioning)
G1 X-20 Y-20 F3000     (move X and Y over a bit at high speed)
G28 X0 Y0              (move X/Y to min endstops)
G1 Z+10 E-5 F400       (move Z up a bit and retract filament by 5mm)
M84                    (steppers off)
G90                    (absolute positioning)
(end of end.gcode)
