(start of end.gcode)
M104 S0                (extruder heat off)
M106                   (fan on)
G91                    (relative positioning)
G1 Z+10 E-5 F400       (move Z up a bit and retract filament by 5mm)
G1 X-20 Y-20 F1500     (move X and Y over a bit)
M84                    (steppers off)
G90                    (absolute positioning)
(end of end.gcode)

