name: Add issues/PRs to backlog automatically

on:
  issues:
    types:
      - opened
      - transferred
  pull_request_target:
    types:
      - opened

permissions: {}

jobs:
  add-to-project:
    name: Add issue or PR to OctoPrint Backlog project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/OctoPrint/projects/6
          github-token: ${{ secrets.BACKLOG_PROJECT_ACCESS }}
