name: "Pull Request Automation"
on:
  pull_request_target:
    types: ["opened"]

permissions:
  pull-requests: write

jobs:
  pr-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: OctoPrint/actions/pr-validation@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
