name: Test install of branches and latest release twice per day

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: read

jobs:
  install-branch:
    name: Install branch
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        branch: ["release", "main", "next", "dev"]
        exclude:
          # main & release: 3.7-3.13
          - branch: "release"
            python: "3.14"
          - branch: "main"
            python: "3.14"
          # next: 3.9-3.14
          - branch: "next"
            python: "3.7"
          - branch: "next"
            python: "3.8"
          # dev: 3.10-3.14
          - branch: "dev"
            python: "3.7"
          - branch: "dev"
            python: "3.8"
          - branch: "dev"
            python: "3.9"
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⬇ Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          path: src
          persist-credentials: false

      - name: 🐍 Set up Python ${{ matrix.python }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python }}

      # Checkout code and install
      - name: ⬇ Checkout code to test
        if: ${{ matrix.branch != 'release' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
          path: checkout
          persist-credentials: false
      - name: 👷 Build and install checkout
        if: ${{ matrix.branch != 'release' }}
        working-directory: checkout
        run: |
          pip install .

      # Install latest release
      - name: 👀 Determine latest release
        if: ${{ matrix.branch == 'release' }}
        run: |
          OCTOPRINT_VERSION=$(curl -i https://github.com/OctoPrint/OctoPrint/releases/latest | grep -i location: | head -n1 | awk -F/ '{print $NF}' | tr -d '\r')
          echo "OCTOPRINT_VERSION=$OCTOPRINT_VERSION" >> $GITHUB_ENV
      - name: 👷 Build and install latest release
        if: ${{ matrix.branch == 'release' }}
        run: |
          pip install https://github.com/OctoPrint/OctoPrint/archive/${OCTOPRINT_VERSION}.zip

      # Test if server starts without error
      - name: 🏗 Create base config for test server
        run: |
          mkdir e2econfig
          cp -r src/.github/ci/e2econfig/* e2econfig

          # ensure enabled rate limiter
          yq -i '.devel.enableRateLimiter = true' e2econfig/config.yaml

      - name: 🧪 Start OctoPrint server
        run: |
          timeout -k 10s 30s octoprint serve --basedir e2econfig &
          wait
      - name: 🔎 Check octoprint.log for errors
        run: |
          log=${{ github.workspace }}/e2econfig/logs/octoprint.log
          if grep "\- ERROR \-" $log; then
            echo "::error::Errors were logged to octoprint.log"
            grep -Pazo '(?m)^\N+\- ERROR \-\N*\n(^\N*?\n)*?(?=\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3} \- )' $log
            exit 1
          fi

      - name: 📧 Discord success notification
        continue-on-error: true
        env:
          DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
        uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554 # 0.4.0
        with:
          args: "☑️ Test install on Python ${{ matrix.python }} under `${{ matrix.os }}` for `OctoPrint/OctoPrint:${{ matrix.branch }}` was successful"
      - name: 📧 Discord failure notification
        continue-on-error: true
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
        uses: Ilshidur/action-discord@d2594079a10f1d6739ee50a2471f0ca57418b554 # 0.4.0
        with:
          args: "🚫 Test install on Python ${{ matrix.python }} under `${{ matrix.os }}` for `OctoPrint/OctoPrint:${{ matrix.branch }}` failed"
