name: Trigger doc build
on:
  push:
    branches:
      - main
      - dev
      - next
  release:
    types:
      - released
      - prereleased

permissions: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: github.repository == 'OctoPrint/OctoPrint'
    steps:
      - name: 🚀 Repository Dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.REPODISPATCH_TOKEN }}
          repository: OctoPrint/docs.octoprint.org
          event-type: docs
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
